platform :ios, '9.0'

target 'BouquetDetection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BouquetDetection
pod 'SwiftyJSON'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
end
